plugins {
    id 'java-library'
    id 'com.gradleup.shadow' version '9.4.1'
    id "com.diffplug.spotless" version "8.4.0"
    id 'application'
}

repositories {
	mavenCentral()
}

dependencies {
	// jda discord api
	implementation("net.dv8tion:JDA:6.5.0") {
      	exclude module: 'opus-java'
      	exclude module: 'tink'
    }
    
    implementation("ch.qos.logback:logback-classic:1.5.32")
	implementation group: 'commons-io', name: 'commons-io', version: '2.22.0'
	implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.20.0'
}

version = project.version

// configure jar
base {
	// change compiled filename
	archivesName = "TASCompetition-Discord-Bot"
}

// set application main class
application {
	mainClass = 'com.minecrafttas.tascomp.main.Main'
}

// compile for java 25
java {
	sourceCompatibility = targetCompatibility = 25
}

spotless {
	encoding "UTF-8"
	lineEndings "UNIX"
	java {
	importOrderFile("formatter/Importorder.txt")
	eclipse().configFile("formatter/Formatter.xml")
	}
	enforceCheck false
}